### ISSUE TITLE
Not able to load services json

### ISSUE THREAD

**Issue by anuj509** [gabor-boros/django-microservices#1]
i have tried loading json but failed.please update docs for clarity.

**Comment by gabor-boros** [comment]
@anuj509 Could you please help me with some details about the following?
* What is the django version
* What was the error message

**Comment by gabor-boros** [comment]
@anuj509 Could you please install the latest version (0.1.2) and test it again? I found and fixed a bug related to relative path of files.

**Comment by gabor-boros** [comment]
Since the issue has been fixed, and there is no update, I'm closing this issue.
